version: '3.1'

services:

  datacloud-backend:
    image: registry.ubitech.eu/maestro/eu-projects/datacloud:1.1.2
    container_name: datacloud-backend
    restart: unless-stopped
    environment:
      QUARKUS_HTTP_PORT: ${QUARKUS_HTTP_PORT}
      MONGODB_PORT: ${MONGODB_PORT}
      MAESTRO_REST_API_URL: ${MAESTRO_REST_API_URL}
      DEFPIPE_REST_API_URL: ${DEFPIPE_REST_API_URL}
      BACKEND_AUTH_SERVER_URL: ${BACKEND_AUTH_SERVER_URL}
      BACKEND_CLIENT_ID: ${BACKEND_CLIENT_ID}
      BACKEND_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET}
      DEF_PIPE_AUTH_SERVER_URL: ${DEF_PIPE_AUTH_SERVER_URL}
      DEF_PIPE_CLIENT_ID: ${DEF_PIPE_CLIENT_ID}
      DEF_PIPE_CLIENT_SECRET: ${DEF_PIPE_CLIENT_SECRET}
      DEF_PIPE_GRANT_USERNAME: ${DEF_PIPE_GRANT_USERNAME}
      DEF_PIPE_GRANT_PASSWORD: ${DEF_PIPE_GRANT_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN_CLIENT: ${KEYCLOAK_ADMIN_CLIENT}
      KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_ADMIN_REALM}
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${QUARKUS_HTTP_PORT}/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: "host"

  mongo:
    image: registry.ubitech.eu/public-group/ubitech-public-registry/mongo:4.4.12
    container_name: datacloud-database
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: