version: '3.7'

services:

  datacloud-backend:
    image: registry.ubitech.eu/maestro/datacloud:1.0.2
    container_name: datacloud-backend
    restart: unless-stopped
    ports:
      - "9500:9500"
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9500/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: registry.ubitech.eu/public-group/ubitech-public-registry/mongo:4.4.12
    container_name: datacloud-database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: