quarkus:
  http:
    port: 9500
    cors:
      ~: true
      origins: "*"
#    same-site-cookie:
#      auth_token:
#        value: none
  tls:
   trust-all: true
  smallrye-openapi:
    info-title: Datacloud
    info-contact-email: info@ubitech.eu
    info-contact-name: UBITECH Ltd.
    info-contact-url: https://ubitech.eu/
    security-scheme: oauth2
    security-scheme-name: Authentication token
    security-scheme-description: Enter you your Keycloak bearer token
  rest-client:
    # Assuming Maestro is running on port 8080
    maestro-rest-api:
      url: http://localhost:8080/
      scope: javax.inject.Singleton
    defpipe-rest-api:
      url: https://crowdserv.sys.kth.se/api/
      scope: javax.inject.Singleton
  swagger-ui:
    always-include: true
  # Securing the current backend
  oidc:
    auth-server-url: https://datacloud-auth.euprojects.net/auth/realms/user-authentication
    client-id: %CLIENTID%
    credentials:
      secret: %SECRET%
    tls:
      verification: none
# Authenticate rest-client fo def-pipe api
  oidc-client:
    auth-server-url: https://datacloud-auth.euprojects.net/auth/realms/user-authentication
    client-id: %CLIENTID%
    credentials:
      secret: %SECRET%
    grant:
      type: password
    grant-options:
      password:
        username: %USER%
        password: %PASSWORD%
    tls:
        verification: none
  mongodb:
    connection-string: mongodb://127.0.0.1:27017
    database: %DATABASE%
"%prod":
  quarkus:
    http:
      port: ${QUARKUS_HTTP_PORT:9500}
      cors:
        ~: true
        origins: "*"
    tls:
      trust-all: true
    smallrye-openapi:
      info-title: Datacloud
      info-contact-email: info@ubitech.eu
      info-contact-name: UBITECH Ltd.
      info-contact-url: https://ubitech.eu/
      security-scheme: oauth2
      security-scheme-name: Authentication token
      security-scheme-description: Enter you your Keycloak bearer token
    rest-client:
      # Assuming Maestro is running on port 8080
      maestro-rest-api:
        url: ${MAESTRO_REST_API_URL}
        scope: javax.inject.Singleton
      defpipe-rest-api:
        url: ${DEFPIPE_REST_API_URL}
        scope: javax.inject.Singleton
    swagger-ui:
      always-include: true
    oidc:
      auth-server-url: ${BACKEND_AUTH_SERVER_URL}
      client-id: ${BACKEND_CLIENT_ID}
      credentials:
        secret: ${BACKEND_CLIENT_SECRET}
      tls:
        verification: none
    oidc-client:
      auth-server-url: ${DEF_PIPE_AUTH_SERVER_URL}
      client-id: ${DEF_PIPE_CLIENT_ID}
      credentials:
        secret: ${DEF_PIPE_CLIENT_SECRET}
      grant:
        type: password
      grant-options:
        password:
          username: ${DEF_PIPE_GRANT_USERNAME}
          password: ${DEF_PIPE_GRANT_PASSWORD}
      tls:
        verification: none
    mongodb:
      connection-string: mongodb://127.0.0.1:${MONGODB_PORT}
      database: %DATABASE%